### ISSUE TITLE
Image.getSize does not work for static images

### ISSUE THREAD

**Issue by markusguenther** [ihor/react-native-scalable-image#1]
Image.getSize does not work for static images and therefore the library will fail when you use static or local images.

**Comment by ihor** [comment]
Hey,

Unfortunately, I don't have much time now to look into it. I created this library to reuse in my projects and my main priorities were to cover my needs. If you know the solution I would be happy to accept a pull request.

**Comment by spoeck** [comment]
I have a solution for this. I will create a pull request very soon!

**Comment by ihor** [comment]
Merged and released. Thanks for the PR @spoeck.

**Comment by markusguenther** [comment]
Awesome ... your are awesome.
