### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [ihor/react-native-scalable-image#12]
Hi. Just upgraded to React Native 0.60 (which uses React 16.8.6) and I get this warning:

> `componentWillReceiveProps` is deprecated and will be removed in the next major version. Use static `getDerivedStateFromProps` instead.
>
> Please update the follwing components: SafeView, ScalableImage, Transitioner
>
> Learn more about this warning here: https://fb.me/react-async-component-lifecycle-hooks

**Comment by ihor** [comment]
Thanks @AlbertVilaCalvo ! The warning is fixed in the latest major version is rewritten with hooks.
