### ISSUE TITLE
does it work inside ScrollView? [not working]

### ISSUE THREAD

**Issue by mezod** [ihor/react-native-scalable-image#13]
literally copied the example and it's not working for an image where height>width. Only possible reason is that it's inside a ScrollView?

**Comment by ihor** [comment]
Hey @mezod ! 

I've never seen such issue before. I've just tested with the latest version and it does work inside a ScrollView for me. Please let me know if you resolved this problem or found the reason. 

Thanks!

**Comment by mezod** [comment]
I ended up doing a custom solution since I couldn't get it to work. Thanks though, if it worked for you I must have done something wrong, I'll just close this :) Cheers
