### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by ikyokushin** [ihor/react-native-scalable-image#17]
I am not sure why this happened.
I think this is because of 
width={Dimensions.get('window').width}

Is there any dependency changes?
![Screen Shot 2020-01-16 at 12 48 24 PM](https://user-images.githubusercontent.com/28947282/72489088-a5534300-385e-11ea-890e-54b3a6962dc6.png)

**Comment by iMiracleDev** [comment]
@ihor , would you like to check it for me?

**Comment by bell-steven** [comment]
I was able to replicate this issue. It was because I was using the WebP format for the image.

**Comment by ihor** [comment]
Closing in favor of https://github.com/ihor/react-native-scalable-image/issues/18
