### ISSUE TITLE
[Question] WebP Support

### ISSUE THREAD

**Issue by bell-steven** [ihor/react-native-scalable-image#18]
I am trying to use this library on iOS with WebP images, and I keep getting the same error as in #17.

What I tried:
Adding the WebP binary to the project.  I was able to load a WebP image in the native `<Image/>` component from `react-native` with this, but It didn't help for `<Image />` from `react-native-scalable-image`. 

On Android it works fine.

Looking at the source code, it seems like the library is wrapping the native `<Image/>' component from 'react-native', so I would have thought that it would work if it works with the native component.

**Comment by swiftserieschannel** [comment]
Any update on this ?
