### ISSUE TITLE
error: Failed to get size for image

### ISSUE THREAD

**Issue by uptotec** [ihor/react-native-scalable-image#23]
when I fetch an image in a flat list I get this error. the error does not show up in all photos, but when it appears the photo doesn't render.

-------------------------------------

Failed to get size for image: https://trackkid.uc.r.appspot.com/data/subject/5eed2b812008fb363d917844/postAttachment/2020-06-20T22:21:39.227Z-postAttachment.png

Stack trace:
  node_modules/react-native/Libraries/YellowBox/YellowBox.js:71:8 in console.warn
  node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
  node_modules/react-native/Libraries/Image/Image.android.js:143:23 in <anonymous>
  node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
  node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
  [native code]:null in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
  ...

code: 

<Image
              source={{
                uri: props.attachmenUrl,
                method: 'GET',
              }}
              width={Dimensions.get('window').width}
            />

------------

![Screenshot_20200621-030046_Expo](https://user-images.githubusercontent.com/38630967/85214510-2661b980-b36c-11ea-9db6-dc26afe81536.jpg)

**Comment by 7dp** [comment]
Hai @uptotec , how do you fix this issue?
Iam experiencing it too

**Comment by erickcrus** [comment]
same here
