### ISSUE TITLE
Is it possible for an image to fill the entire device height depending on the aspect ratio

### ISSUE THREAD

**Issue by aleluiah** [ihor/react-native-scalable-image#25]
hi, thanks for the awesome package, i am working on a flatlist newsfeed component the and am using this package to render images on my flatlist component, am worried if the image will cover the entire height of the device screen, please is it possible

**Comment by ihor** [comment]
@aleluiah , the following code should do the job:
```
import React from 'react';
import { Dimensions } from 'react-native';
import Image from 'react-native-scalable-image';
 
const image = (
   <Image
       height={Dimensions.get('window'). height} // width will be calculated automatically
       source={{uri: '<image uri>'}}
   />
);
```
