### ISSUE TITLE
Support for this project

### ISSUE THREAD

**Issue by spoeck** [ihor/react-native-scalable-image#3]
@ihor 
Hi and thanks for your work.
I made a pull request some weeks ago. Please let me know what you think about it.
If you are not supporting this project anymore I will publish my fork as separate npm package but I prefer to enhance the origin one.
So please let me know if you want to continue your work on this project.
cheers, spoeck

**Comment by ihor** [comment]
Thank you, I merged the pull request.

Sorry for the late response, vacation season.
